function [cfg_artifact] = JOEI_mergeThArtResults(cfg_artifact1, cfg_artifact2)
% JOEI_MERGEARTIFACTRESULTS is a functions which merges two artifact
% specification structures into on common one. These function is useful,
% when e.g. for certain channels (V1, V2) another threshold value has to be
% used.
%
% Use as
%   [cfg_artifact] = JOEI_mergeThArtResults(cfg_artifact1, cfg_artifact2)
%
% where the input data elements has to be a result of JOEI_AUTOARTIFACT
%
% This function requires the fieldtrip toolbox.
%
% See also JOEI_AUTOARTIFACT

% Copyright (C) 2019, Daniel Matthes, MPI CBS

% -------------------------------------------------------------------------
% check input - only threshold artifacts should be merged
% -------------------------------------------------------------------------
if ~isfield(cfg_artifact1.artfctdef, 'threshold')
  error('cfg_artifact1 has no threshold artifacts. Nothing to merge.');
end

if ~isfield(cfg_artifact2.artfctdef, 'threshold')
  error('cfg_artifact2 has no threshold artifacts. Nothing to merge.');
end

% test if both artifact specification structures were generated by using
% the same dataset
if size(cfg_artifact1.artfctdef.threshold.trl, 1) ~= ...
    size(cfg_artifact2.artfctdef.threshold.trl, 1)
  error(['The input structures have different trl specifications. '...
          'Merging is not possible!']);
end

% -------------------------------------------------------------------------
% merge input structures
% -------------------------------------------------------------------------
cfg_artifact = cfg_artifact1;

cfg_artifact.artfctdef.threshold = removefields( ...
  cfg_artifact.artfctdef.threshold, {'channel', 'range', 'artifact'});

cfg_artifact.artfctdef.threshold.channel1 = ...                             % add both channel specifications
  cfg_artifact1.artfctdef.threshold.channel;
cfg_artifact.artfctdef.threshold.channel2 = ...
  cfg_artifact2.artfctdef.threshold.channel;

cfg_artifact.artfctdef.threshold.range1 = ...                               % add both range values
  cfg_artifact1.artfctdef.threshold.range;
cfg_artifact.artfctdef.threshold.range2 = ...
  cfg_artifact2.artfctdef.threshold.range;

artifact = [ cfg_artifact1.artfctdef.threshold.artifact; ...                % concatenate artifact specifications
  cfg_artifact2.artfctdef.threshold.artifact ];

if ~isempty(artifact)                                                       % sort values in a ascending order and remove duplicates
  [~,idx] = sort(artifact(:,1));
  artifact = artifact(idx, :);

  if size(artifact, 1) > 1
    idx       = [true; sum(diff(artifact),2) ~= 0];
    artifact  = artifact(idx,:);
  end
end

cfg_artifact.artfctdef.threshold.artifact = artifact;

cfg_artifact.badNum = size(...                                              % update numbers of bad channels
                    cfg_artifact.artfctdef.threshold.artifact, 1);

end
